# ATT System Docker Compose - Production Configuration
version: '3.8'

services:
  metrics-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: att-system/metrics-api:latest
    container_name: att-metrics-api
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
    volumes:
      # Mount data files read-only for metrics processing
      - ./cost-tracking.json:/app/data/cost-tracking.json:ro
      - ./cost-tracking.jsonl:/app/data/cost-tracking.jsonl:ro
      - ./error-log.json:/app/data/error-log.json:ro
      - ./error-log.jsonl:/app/data/error-log.jsonl:ro
      - ./SMOKE_TEST_RESULTS.md:/app/data/SMOKE_TEST_RESULTS.md:ro
      # Additional test result files if they exist
      - ./tests/fixtures:/app/data/fixtures:ro
    networks:
      - att-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    image: att-system/dashboard:latest
    container_name: att-dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      metrics-api:
        condition: service_healthy
    networks:
      - att-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  att-network:
    driver: bridge
    name: att-system-network

# Named volumes for persistence (if needed in future)
volumes:
  api-logs:
    name: att-api-logs
  dashboard-logs:
    name: att-dashboard-logs