name: Nightly Real-Mode Smoke Tests

on:
  schedule:
    - cron: '0 2 * * *'  # Daily at 02:00 UTC
  workflow_dispatch:     # Allow manual trigger

env:
  SMOKE_TEST_COST_THRESHOLD: 0.02

jobs:
  nightly-real-smoke:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run real-mode smoke tests (agents #28, #29 only)
      env:
        GRAMMARLY_API_KEY: ${{ secrets.GRAMMARLY_API_KEY }}
      run: npm run smoke-test:real
      
    - name: Check for cost overrun
      run: |
        if grep -q "WARNING.*cost exceeded" SMOKE_TEST_RESULTS.md; then
          echo "💰 ALERT: Nightly smoke tests exceeded cost threshold"
          exit 1
        fi
      
    - name: Upload nightly smoke test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: nightly-smoke-results-${{ github.run_number }}
        path: |
          SMOKE_TEST_RESULTS.md
          cost-tracking.json
          error-log.jsonl
        retention-days: 7
      
    - name: Parse cost and check overrun
      id: cost-check
      if: always()
      run: |
        if [ -f SMOKE_TEST_RESULTS.md ]; then
          if grep -q "WARNING.*cost exceeded" SMOKE_TEST_RESULTS.md; then
            echo "overrun=true" >> $GITHUB_OUTPUT
            COST=$(grep -o '\$[0-9.]*' SMOKE_TEST_RESULTS.md | head -1)
            echo "cost=${COST:-unknown}" >> $GITHUB_OUTPUT
          fi
        fi

    - name: Slack notification on failure
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        text: "🌙 Nightly Real-Mode Tests FAILED | Check artifacts"
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Slack notification on cost overrun
      if: steps.cost-check.outputs.overrun == 'true'
      uses: 8398a7/action-slack@v3
      with:
        status: warning
        text: "💰 Nightly tests exceeded $0.02: ${{ steps.cost-check.outputs.cost }}"
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Email notification on critical failure
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_FROM }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "🌙 ATT System: Nightly Tests Failed"
        body: "Nightly real-mode tests failed. Check: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        to: ${{ secrets.EMAIL_TO }}
        from: ${{ secrets.EMAIL_FROM }}